# bofore
# sudo docker run --rm -it --user "$(id -u):$(id -g)" -v "$(pwd)/config:/home/node/.openclaw" openclaw-dev:latest openclaw setup
# after
# sudo docker-compose up -d 
services:
  openclaw:
    image: openclaw-dev:latest
    container_name: openclaw
    restart: unless-stopped
    ports:
      - "18789:18789"
    volumes:
      - ./data:/data
      - ./config:/home/node/.openclaw
    user: "${UID:-1000}:${GID:-1000}"
    command: ["openclaw", "gateway"]
    networks:
      - openclaw_net

networks:
  openclaw_net:
    driver: bridge

# docker compose exec openclaw openclaw devices list && docker compose exec openclaw openclaw devices approve --latest
# sudo docker exec -it openclaw npx -y @larksuite/openclaw-lark install
# sudo usermod -aG docker mercury


# Commands:
#  docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml logs -f openclaw-gateway
#  docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml exec openclaw-gateway node dist/index.js health --token "ef3667800017ac8bde4ecd45428670e64c3fb5fdbddf1f9d460f7390e4c5eef2"
#  docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml logs -f openclaw-cli 

#  export OPENCLAW_CONFIG_DIR=/home/luo/soft/docker/openclaw-config/

# Commands:
#  docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml logs -f openclaw-gateway
#  docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml exec openclaw-gateway node dist/index.js health --token "ef3667800017ac8bde4ecd45428670e64c3fb5fdbddf1f9d460f7390e4c5eef2"

# docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml 
# docker compose exec openclaw-gateway openclaw devices list && docker compose exec openclaw-gateway openclaw devices approve --latest
# docker compose -f /home/luo/soft/docker/openclaw/docker-compose.yml exec openclaw-gateway openclaw gateway restart

# https://192.168.1.90/chat?session=agent%3Amain%3Amain&token=ef3667800017ac8bde4ecd45428670e64c3fb5fdbddf1f9d460f7390e4c5eef2

# docker restart openclaw-openclaw-gateway-1