version: '3.8'

services:
  embedding:
    image: vllm/vllm-openai:latest
    container_name: qwen3-embedding-4b
    ports:
      - "30002:8000"                    # 注意端口改为 30001，避免与 sglang 冲突
    volumes:
      - /mnt/hdd3/llm/Qwen:/Qwen:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    runtime: nvidia
    restart: unless-stopped
    shm_size: 16g
    command: >
      --model /Qwen/Qwen3-Embedding-4B
      --served-model-name Qwen3-Embedding-4B
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 1
      --max-model-len 4096
      --dtype auto
      --gpu-memory-utilization 0.75

# 8GB