services:
  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      apisix:
    depends_on:
      - etcd

  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - apisix-data:/usr/local/apisix/logs
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./conf/jwt-rsa256-public.pem:/usr/local/apisix/conf/public.pem
      - ./plugins/rs256-jwt-auth.lua:/usr/local/apisix/apisix/plugins/rs256-jwt-auth.lua
      - ./plugins/aes-request-decode.lua:/usr/local/apisix/apisix/plugins/aes-request-decode.lua
      - ./plugins/aes-response-encode.lua:/usr/local/apisix/apisix/plugins/aes-response-encode.lua
    environment:
      - LD_LIBRARY_PATH=/usr/local/openresty/openssl3/lib/
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9180:9180/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:latest
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  web1:
    image: nginx:1.28.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  web2:
    image: nginx:1.28.0-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      apisix:

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
  apisix-data:
