services:
  comfyui_9012:
    image: "192.168.1.100:5000/cuda/comfyui:v0.0.2"
    container_name: comfyui-9012
    volumes:
      - ./ComfyUILatest:/app
      - /mnt/hdd2/models:/app/models
      - ./output:/app/output
      - ./input:/app/input
      - ./.venv1:/app/.venv
    ports:
      - "9012:9012"
    environment:
      - "DEVICE=3"
      - "LISTEN=0.0.0.0"
      - "PORT=9012"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    stdin_open: true
    tty: true
    command: "/bin/sh"
    # command: "/app/python main.py --listen 0.0.0.0 --port 8188 --cuda-device 0 --output-directory /output --input-directory /input"


# deploy.resources.reservations.devices: 定义设备资源预留
# driver: nvidia: 指定使用 NVIDIA 驱动
# count: all: 相当于 --gpus all
# capabilities: [gpu]: 指定 GPU 能力