# sudo docker compose -f ./mysql-compose.yml up -d
services:
  mysql:
    restart: unless-stopped
    container_name: mysql
    image: "mysql:8.0.44"
    environment:
      - MYSQL_ROOT_PASSWORD=LHPeXJZ7JqvLiQTC
    ports:
      - "3308:3306"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    user: "1000:1000"

# sudo chown -R 999:999 ./data ./logs
# sudo chmod -R 777 ./data ./logs