services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:8080"
    volumes:
      - ./logs:/home/nacos/logs
      - ./data:/home/nacos/data
    restart: unless-stopped
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=test
      - NACOS_AUTH_IDENTITY_VALUE=test
      - NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey0945029898563945898453485676578974525
      
      # JVM参数设置
      - JVM_XMS=2g
      - JVM_XMX=2g
      - JVM_XMN=256m
      - JVM_MS=128m
      - JVM_MMS=256m
# sudo docker run --name nacos -itd 
# -e MODE=standalone 
# -e NACOS_AUTH_ENABLE=true 
# -e NACOS_AUTH_IDENTITY_KEY=test 
# -e NACOS_AUTH_IDENTITY_VALUE=test 
# -e NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE=true 
# -e NACOS_AUTH_TOKEN=SecretKey0945029898563945898453485676578974525 
# -v /mnt/hdd/docker/nacos:/home/nacos/logs 
# -p 8848:8848 -p 9848:9848 -p 9849:9849 --net uunet --ip 172.18.0.40 nacos/nacos-server:2.0.3