services:
  api:
    image: "hyperf/hyperf:8.1-alpine-v3.18-swoole"
    container_name: php-api
    volumes:
      - ./api:/web
    ports:
      - "9511:9511"
      - "9512:9512"
      - "9513:9513"
    restart: unless-stopped
    command: "php /web/bin/hyperf.php start"
    user: "1000:1000"
  rpc:
    image: "hyperf/hyperf:8.1-alpine-v3.18-swoole"
    container_name: php-rpc
    volumes:
      - ./rpc:/web
    ports:
      - "9521:9521"
      - "9522:9522"
      - "9523:9523"
    restart: unless-stopped
    command: "php /web/bin/hyperf.php start"
    user: "1000:1000"
  work:
    image: "hyperf/hyperf:8.0-alpine-v3.12-swoole"
    container_name: php-work
    volumes:
      - ./work/admin:/web
    ports:
      - "9531:9531"
      - "9532:9532"
      - "9533:9533"
    restart: unless-stopped
    command: "php /web/bin/hyperf.php start"
    user: "1000:1000"